### ISSUE TITLE
Publish test coverage reports in CI

### ISSUE THREAD

**Issue by michalrus** [blockfrost/blockfrost-platform#254]
## Context

We already have test coverage with `cargo-tarpaulin`:
* #243 

It would be good to:

* [x] Run it also on CI – see https://github.com/blockfrost/blockfrost-platform/pull/243#issuecomment-2735871641).
 
* [ ] Publish the HTML reports somewhere in the PR – maybe an updated comment like the ones from **@cloudflare-workers-and-pages**.

* [x] Maybe fail the build when coverage drops below a certain percentage, which we’d increase from time to time.

**Comment by vladimirvolek** [comment]
```
coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate coverage report
        run: cargo tarpaulin --lib --features tarpaulin --out html

```
